[package]
name = "fspg"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fsextra = { version = "0.3.0-alpha.0", features = ["crypto"] }
hex = "0.4.0"